### ISSUE TITLE
Create a city roof with parallax scrolling

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/tenebris#18]
The whole game will have a common city roof layer that has three visible layers with parallax scrolling.
To handle endless scrolling of the roof layer, refer to [this](https://github.com/DarkFalc0n/phaser-tutorial/blob/master/game.js#L68)

Reference Image: 
![image](https://github.com/DarkFalc0n/tenebris/assets/59203815/f548f080-9550-417a-894f-9599789334c3)

**Comment by ATLAS2002** [comment]
Implemented this feature in PR #21
