### ISSUE TITLE
fix hardcoded part

### ISSUE THREAD

**Issue by ATLAS2002** [DarkFalc0n/tenebris#4]
```ts
// src/scenes/Boot.ts
const platform = this.physics.add.staticGroup();
    platform
      .create(
        0,
        this.player.y + this.player.height,
        "player",
        0,
      )
      .refreshBody()
      .setSize(2000, 1);
```
### What seems to be the problem:
Setting the size `this.sys.game.config.height` is resulting into the platform being too short for the player to walk around.
### Current solution:
Current fix is setting it to a relatively larger value (2000 works fine here).

**P.S: feel free to close this issue as it may not be important and require a lot of debugging, but if it's a common fix then go ahead**

**Comment by DarkFalc0n** [comment]
We can remove the platform later and replace it with a tilemap and add it to a physics group right?

**Comment by ATLAS2002** [comment]
> We can remove the platform later and replace it with a tilemap and add it to a physics group right?

that is the plan, yes. It is only there as a placeholder for now.

**Comment by DarkFalc0n** [comment]
then this issue is not worth looking into right now
